# Site
# Content configuration version
version: 2

# Personal info
name: Luis Enrique Pérez Villaseñor
title: Estudiante
email: fischer1v9@hotmail.com
website: https://fischer1v9.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username:
github_username:  Fischer1v9
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username:
# linkedin_username:
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username:
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
# icon: fas fa-globe
# url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mí
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Me llamo Enrique, soy estudiante de Ingeniería Informática. No tengo mucha experiencia, pero estamos aprendiendo. 
  Soy habilidoso en: <mark>Unity</mark> y <mark>Usar chat GPT</mark>

content:
  
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<center>No tengo experiencia</center>"

  - title: Educación 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2021 - 2023
        sub_title: Ingenieria informatica
        description: | # this will include new lines to allow paragraphs
          Entré a la Universidad de Guadalajara en 2021, pero debido a una enfermedad en el cerebro, solicité una licencia de 6 meses para recuperarme física y mentalmente. Al regresar, tuve la oportunidad de cursar varias materias que me han proporcionado experiencia y conocimiento. En mi opinión, hay dos clases de la carrera que recuerdo especialmente porque no solo aprendí mucho en ellas, sino que también me divertí mucho.
          Una de ellas fue la clase de Estructuras de Datos con el profesor Alfredo Gutiérrez, y la otra fue la clase de Hipermedia con el profesor Camarena. En esta última materia, aprendí a utilizar Unity.

  - title: Un poco sobre mí.
    layout: text
    content: | # this will include new lines to allow paragraphs
      Además de mis intereses en redes e ingeniería de software, algunos de mis otros intereses y pasatiempos son:

      - Videojuegos competitivos
      - [Correr con mi perro](https://gyazo.com/ba1fec552383577d4e2a851ece5aa43c)
      - Temas militares
      - Salir con amigos

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
