# Site
# Content configuration version
version: 2

# Personal info
name: Luis Enrique Perez Villasenor
title: Estudiante
email: fischer1v9@hotmail.com
website: https://fischer1v9.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username:
github_username:  Fischer1v9
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username:
# linkedin_username:
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username:
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
# icon: fas fa-globe
# url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Me llamo Enrique, soy estudiante de ingenieria informatica, no tengo mucha experiencia pero estamos aprendiendo.
  Soy mas habilidoso en: <mark>Unity</mark> y <mark>Usar chat GPT</mark>

content:
  
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: No tengo experiencia.

  - title: Educacion
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2021 - 2023
        sub_title: Ingenieria informatica
        description: | # this will include new lines to allow paragraphs
          Entre a La Universidad de Guadalajara en 2021 pero por una enfermedad en el cerebro pedi una licencia de 6 meses, tuve que recuperarme fisica y mentalmente. Ya al entrar bien pase por varias materias
          que me han dado un poco de experiencia y conocimiento, en mi opinion hay dos clases de la carrera que recuerdo bien porque ademas de que son en las que mas he aprendido son las que mas me he divertido,
          Una de ellas fue la clase de Estructuras de datos con Alfredo Gutiérrez e Hipermedia con Camarena (aqui aprendi a usar Unity).

  - title: Un poco de mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Además de mis intereses en redes e ingeniería de software, algunos de mis otros intereses y pasatiempos son:
      - Videojuegos competitivos
      - Correr con mi perro
      - Tema militar
      - Terrorismo

      Mira esta imagen  
      ![Trees]( Fischer1v9.github.io/im.jfif "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
